# Generated by Django 4.2.2 on 2023-07-04 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='mosaicpay.account')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='TransactionState',
            fields=[
                ('transaction_state_id', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=9, unique=True)),
            ],
            options={
                'verbose_name': 'TransactionState',
                'verbose_name_plural': 'TransactionStates',
                'db_table': 'transaction_state',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birthday', models.DateField(null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'UserRole',
                'verbose_name_plural': 'UserRoles',
                'db_table': 'user_role',
            },
        ),
        migrations.CreateModel(
            name='TransactionChangesLog',
            fields=[
                ('transaction_changes_log_id', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('change_type', models.CharField(max_length=255)),
                ('change_date', models.DateField(auto_now=True)),
                ('changed_by_user', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='mosaicpay.user')),
                ('transaction', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='mosaicpay.transaction')),
            ],
            options={
                'verbose_name': 'TransactionChangesLog',
                'verbose_name_plural': 'TransactionChangesLogs',
                'db_table': 'transaction_changes_log',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_state',
            field=models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='mosaicpay.transactionstate'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2048, unique=True)),
                ('user', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='mosaicpay.user')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='AccountChangesLog',
            fields=[
                ('account_changes_log_id', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('change_type', models.CharField(max_length=255)),
                ('change_date', models.DateField(auto_now=True)),
                ('account', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='mosaicpay.account')),
                ('changed_by_user', models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='mosaicpay.user')),
            ],
            options={
                'verbose_name': 'AccountChangesLog',
                'verbose_name_plural': 'AccountChangesLogs',
                'db_table': 'account_changes_log',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(max_length=4, on_delete=django.db.models.deletion.CASCADE, to='mosaicpay.user'),
        ),
        migrations.CreateModel(
            name='UserRoleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaicpay.user')),
                ('user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mosaicpay.userrole')),
            ],
            options={
                'db_table': 'user_role_user',
                'unique_together': {('user', 'user_role')},
            },
        ),
    ]
