# Generated by Django 4.2.2 on 2023-07-06 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mosaicpay', '0002_alter_accountchangeslog_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountchangeslog',
            name='account',
            field=models.ForeignKey(max_length=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosaicpay.account'),
        ),
    ]
