# Generated by Django 4.2.2 on 2023-07-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosaicpay', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyEntity',
        ),
    ]
