# Generated by Django 4.2.2 on 2023-07-06 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mosaicpay', '0003_alter_accountchangeslog_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accountchangeslog',
            name='account_changes_log_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionchangeslog',
            name='transaction',
            field=models.ForeignKey(max_length=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosaicpay.transaction'),
        ),
        migrations.AlterField(
            model_name='transactionchangeslog',
            name='transaction_changes_log_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionstate',
            name='transaction_state_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user_role_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
