# Generated by Django 4.2.2 on 2023-07-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaicpay', '0005_alter_user_managers_user_date_joined_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(default='jpg', max_length=4),
        ),
    ]
