# Generated by Django 4.2.2 on 2023-07-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosaicpay', '0007_document_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.FileField(null=True, upload_to='storage/'),
        ),
    ]
